apiVersion: v1
kind: ReplicationController
metadata:
  name: ottemo-io
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "ottemo-io"
        server_name: "ottemo.io"
    spec:
      containers:
      - name: ottemo-io
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        image: gcr.io/ottemo-kube/ottemo-io:20170404-134139
        ports:
        - containerPort: 80
        - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: ottemo-io
  labels:
    app: "ottemo-io"
    server_name: "ottemo.io"
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  type: NodePort
  selector:
    app: ottemo-io


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ottemo-io
  labels:
    app: "ottemo-io"
    server_name: "ottemo.io"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - ottemo.io
    - www.ottemo.io
    secretName: ottemo-io-tls
  backend:
    serviceName: ottemo-io
    servicePort: 80
